import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

/**
 * MODEL-ROOT-MOTION — **the root bone stays near the body it belongs to.**
 *
 * Owner Dev Notes (2026-10-08): *"Wisp is floating above the ground and is
 * outside of her tile confines"* and *"Wisp's arm is clipping weirdly through
 * her body in the idle animation"*. Both were one broken asset. The shipped
 * `wisp.glb` had Hips tracks reaching **102 units** from a bind pose 1.09 units
 * off the floor — on a rig whose whole body is 1.9 units tall. She was not
 * posed wrongly; she was thrown a hundred metres and drawn wherever the clip
 * left her.
 *
 * That number is the check. A character clip may genuinely travel — Aegis's
 * `knocked_down` carries him 1.7 units, Wisp's 2.5 — and it may not travel a
 * hundred. Two model-heights is an order of magnitude below the failure and
 * over 1.5x above the largest honest clip in the roster, so it separates the
 * two without needing a magic number in metres.
 *
 * Worth a standing test rather than a one-off measurement because
 * `public/models/` is the one place in this repo where a **build artifact is a
 * committed source file** — written on somebody's machine, pushed by hand,
 * regenerated by nothing on CI. The corruption was invisible in every existing
 * check: the file loaded, the manifest matched, the clip list was right, and
 * MODEL-ROOT-LOCK papered over it at runtime by pinning every axis. Reading the
 * bytes is the only place it shows.
 */

const MODELS = new URL('../public/models/', import.meta.url).pathname;
/** Character rigs only — props (`aegis_door`, `wisp_dagger`) have no skeleton. */
const rigs = existsSync(MODELS)
  ? readdirSync(MODELS)
    .filter((f) => f.endsWith('.clips.json'))
    .map((f) => f.replace('.clips.json', '.glb'))
    .filter((f) => existsSync(join(MODELS, f)))
  : [];

interface Gltf {
  nodes: { name?: string; translation?: number[]; children?: number[] }[];
  meshes: { primitives: { attributes: Record<string, number> }[] }[];
  accessors: { bufferView: number; byteOffset?: number; count: number; type: string; min?: number[]; max?: number[] }[];
  bufferViews: { byteOffset?: number; byteStride?: number }[];
  animations?: { name?: string; samplers: { input: number; output: number }[]; channels: { sampler: number; target: { node?: number; path: string } }[] }[];
}

/** The JSON chunk and the BIN chunk of a `.glb`. */
function readGlb(path: string): { json: Gltf; bin: Buffer } {
  const buf = readFileSync(path);
  expect(buf.subarray(0, 4).toString('ascii'), `${path} is not a .glb`).toBe('glTF');
  let off = 12;
  let json: Gltf | undefined;
  let bin = Buffer.alloc(0);
  while (off < buf.length) {
    const length = buf.readUInt32LE(off);
    const kind = buf.readUInt32LE(off + 4);
    const chunk = buf.subarray(off + 8, off + 8 + length);
    off += 8 + length;
    if (kind === 0x4e4f534a) json = JSON.parse(chunk.toString('utf8')) as Gltf;
    else if (kind === 0x004e4942) bin = chunk;
  }
  expect(json, `${path} has no JSON chunk`).toBeDefined();
  return { json: json!, bin };
}

/** One accessor's rows of floats, de-interleaved. */
function rows(g: Gltf, bin: Buffer, index: number): number[][] {
  const acc = g.accessors[index]!;
  const view = g.bufferViews[acc.bufferView]!;
  const start = (view.byteOffset ?? 0) + (acc.byteOffset ?? 0);
  const n = { SCALAR: 1, VEC3: 3, VEC4: 4 }[acc.type] ?? 1;
  const stride = view.byteStride ?? 4 * n;
  return Array.from({ length: acc.count }, (_, i) =>
    Array.from({ length: n }, (_, c) => bin.readFloatLE(start + i * stride + c * 4)));
}

/** How tall the rig's mesh is, from its POSITION bounds — the same measure `modelBounds` takes. */
function meshHeight(g: Gltf): number {
  let low = Infinity;
  let high = -Infinity;
  for (const mesh of g.meshes ?? []) {
    for (const prim of mesh.primitives) {
      const acc = g.accessors[prim.attributes['POSITION']!]!;
      if (acc.min === undefined || acc.max === undefined) continue;
      low = Math.min(low, acc.min[1]!);
      high = Math.max(high, acc.max[1]!);
    }
  }
  return high > low ? high - low : 0;
}

/** Furthest any clip moves the root bone from where the bind pose put it. */
function worstDrift(g: Gltf, bin: Buffer): { distance: number; clip: string } {
  const hips = g.nodes.findIndex((n) => /Hips$/.test(n.name ?? ''));
  if (hips < 0) return { distance: 0, clip: '' };
  const bind = g.nodes[hips]!.translation ?? [0, 0, 0];
  let distance = 0;
  let clip = '';
  for (const anim of g.animations ?? []) {
    for (const channel of anim.channels) {
      if (channel.target.node !== hips || channel.target.path !== 'translation') continue;
      for (const v of rows(g, bin, anim.samplers[channel.sampler]!.output)) {
        const d = Math.hypot(v[0]! - bind[0]!, v[1]! - bind[1]!, v[2]! - bind[2]!);
        if (d > distance) { distance = d; clip = anim.name ?? '?'; }
      }
    }
  }
  return { distance, clip };
}

describe('MODEL-ROOT-MOTION: no committed rig throws its root bone off the map', () => {
  if (rigs.length === 0) {
    it('no rigs are committed yet, which is a valid state', () => {
      expect(rigs).toEqual([]);
    });
  }

  it.each(rigs)('%s keeps every clip within two model-heights of the bind pose', (file) => {
    const { json, bin } = readGlb(join(MODELS, file));
    const height = meshHeight(json);
    expect(height, 'the rig has no measurable mesh').toBeGreaterThan(0);
    const { distance, clip } = worstDrift(json, bin);
    expect(distance, `"${clip}" drifts ${distance.toFixed(2)} against a ${height.toFixed(2)} body`)
      .toBeLessThan(height * 2);
  });

  it.each(rigs)('%s has a root bone with a bind translation to measure against', (file) => {
    // The pairing that stops the assertion above passing for free. A rig whose
    // Hips node were missing, or renamed, would report a drift of zero — which
    // is "no root motion" and "no measurement" wearing the same number.
    const { json } = readGlb(join(MODELS, file));
    const hips = json.nodes.find((n) => /Hips$/.test(n.name ?? ''));
    expect(hips, 'no Hips bone').toBeDefined();
    expect(hips!.translation, 'Hips has no bind translation').toBeDefined();
  });
});
